spring.application.name=RD_SYSTEM_INTERNSHIP

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/RECURRING_DEPOSIT_SYSTEM
spring.datasource.username=postgres
spring.datasource.password=Aman@9598
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.devtools.restart.enabled=false

#spring security
#spring.security.user.name=aman
#spring.security.user.password=pass