spring.application.name=RD_SYSTEM_INTERNSHIP

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-snowy-pine-angvg1zo-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_51XqiJoIUuFm
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

spring.devtools.restart.enabled=false